[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "W/etag"

[[headers]]
  for = "/Build/*.js.br"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "W/etag"

[[headers]]
  for = "/Build/*.data.br"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "W/etag"

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/download"
  to = "/.netlify/functions/redirect"
  status = 200