[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "W/etag"

[[headers]]
  for = "/Build/*.js.br"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "W/etag"

[[headers]]
  for = "/Build/*.data.br"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "W/etag"

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/petman"
  to = "/.netlify/functions/redirect"
  status = 200

  [[redirects]]
  from = "/mbtidownload"
  to = "/.netlify/functions/mbti_redirect"
  status = 200

  [[redirects]]
  from = "/autogram_download"
  to = "/.netlify/functions/tagai_redirect"
  status = 200

  [[redirects]]
  from = "/autogram_privacy"
  to = "/.netlify/functions/tagai_privacy_redirect"
  status = 200

  [[redirects]]
  from = "/autogram_terms"
  to = "/.netlify/functions/tagai_terms_redirect"
  status = 200

  [[redirects]]
  from = "/tagai_download"
  to = "/.netlify/functions/tagai_redirect"
  status = 200

  [[redirects]]
  from = "/tagai_privacy"
  to = "/.netlify/functions/tagai_privacy_redirect"
  status = 200

  [[redirects]]
  from = "/tagai_terms"
  to = "/.netlify/functions/tagai_terms_redirect"
  status = 200